CREATE TABLE notes (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    content VARCHAR(255) NOT NULL,
    CONSTRAINT NOTES_TITLE_LENGTH CHECK(LENGTH(title)>=3 AND LENGTH(title) <= 150),
    CONSTRAINT NOTES_CONTENT_LENGTH CHECK(LENGTH(content)>=3 AND LENGTH(content) <= 255)
);
